%% Script in progress of CueLocking experiment...

Params.MotherDirectory = get_working_pc_and_directory ('/home/giulio/Sdrive/DBIO_BarryLab_DATA/giulioC/Data/VR/CueLocking','S:\DBIO_BarryLab_DATA\giulioC\Data\VR\CueLocking');
Params.MatlabOutoutDirectory = 'MatlabOutput\';
Params.MatlabOutoutDirectory = [Params.MotherDirectory  Params.MatlabOutoutDirectory] ;
mkdir(Params.MatlabOutoutDirectory);   

ReRunDataSet = 0 ;
LoadDataSet = 1 ; 
LoadDataSetAlreadyRun = 0 ; 
ExtractCells = 0;
SaveTheta = 1;
NShuffles = 100;
RunSarahVersion = 0;
Method = 'SpikeShuffle';
NShuffles = 100;
OpenFieldShuffles = 100 ;
AllCells = [];
CueLockingTable = { ...
'CueLocking','m3193','20180205', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[]     , Method,OpenFieldShuffles ;...
'CueLocking','m3193','20180209', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[]     , Method,OpenFieldShuffles ;...
'CueLocking','m3193','20180220', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[]     , Method,OpenFieldShuffles ;...
'CueLocking','m3193','20180223', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[]     , Method,OpenFieldShuffles ;...
'CueLocking','m3193','20180226', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[]     , Method,OpenFieldShuffles ;...
'CueLocking','m3194','20180212', 1 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[9:16] , Method,OpenFieldShuffles ;...
'CueLocking','m3194','20180220', 1 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[9:16] , Method,OpenFieldShuffles ;...
'CueLocking','m3194','20180223', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[9:16] , Method,OpenFieldShuffles ;...
'CueLocking','m3194','20180226', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[9:16] , Method,OpenFieldShuffles ;...
'CueLocking','m3500','20180430', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[9:16] , Method,OpenFieldShuffles ;...
'CueLocking','m3500','20180501', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[9:16] , Method,OpenFieldShuffles ;...
'CueLocking','m3504','20180419', 0 ,ReRunDataSet,LoadDataSet , LoadDataSetAlreadyRun,  ExtractCells,  SaveTheta,       NShuffles ,RunSarahVersion ,[1:8],[]     , Method,OpenFieldShuffles ;;...
};

for iSession = 1 %:  size(CueLockingTable,1)
    Output = DisplayCellsFromVR(...
    CueLockingTable{iSession,1},...
    CueLockingTable{iSession,2},...
    CueLockingTable{iSession,3},...
    cell2mat(CueLockingTable(iSession,4)), ...
    cell2mat(CueLockingTable(iSession,5)), ...
    cell2mat(CueLockingTable(iSession,6)), ... 
    cell2mat(CueLockingTable(iSession,7)), ...
    cell2mat(CueLockingTable(iSession,8)), ...
    cell2mat(CueLockingTable(iSession,9)), ...
    cell2mat(CueLockingTable(iSession,10)),...
    cell2mat(CueLockingTable(iSession,11)),...
    cell2mat(CueLockingTable(iSession,12)),...
    cell2mat(CueLockingTable(iSession,13)));
  
AllCells = [AllCells;Output];
clear Output;
end;
for iSession = 1 : numel(AllCells);
    
    AllCells(iSession).Parameters.MEC_Tetrodes = CueLockingTable{iSession,12};
    AllCells(iSession).Parameters.HPC_Tetrodes = CueLockingTable{iSession,13};
    
end
clear iSession;
cd(MatlabOutoutDirectory);
%save('AllCells','AllCells','-v7.3');



WrapUpBehaviourFromCueLockingSessions



CodeForWrappingCueLockingResults;
%% 

%% Charlie's experiment, but it requires extra processing...
% DisplayCellsFromVR('TeleTunnel','m3193','20171218', 0) ;
% DisplayCellsFromVR('TeleTunnel','m3193','20171219', 0) ;



%% Missing results:

% Do cue-locked cells fire in the same location relative to the subcompartment?
% Are they theta modulated? If so, do they show PP ?
% 
% 
% Tetrode = 2;
% Cell = 4;
% iSession = 3;
% eval([ 'VR = VRs.Session_' num2str(iSession) ';'] );
% iCell = 14;
% eval(['RateMap = AllCells(iCell).Session_' num2str(iSession) ';' ]);;
% subplot1 = [2,1,1];subplot2 = [2,1,2];
% ProduceFourierTransform(VR, RateMap,Tetrode,Cell,SpikeColor,RateMapLineWidth,Boundaries,Compartments,ForEachCompartmentVisits,1,'Giulio',[subplot1],[subplot2]);

