function [vr ] = TeleTunnelTrialSettings(vr)
%% Specify a bunch of props such number of trials ecc...
vr.TrialSettings.movementFunctionAfterPause = vr.exper.movementFunction;
vr.exper.movementFunction = vr.TrialSettings.movementFunctionAfterPause;
%vr.experimentEnded= ~strcmp(vr.exper.worlds{vr.currentWorld}.name,'FirstIntermediatePipe');
vr.TrialSettings.MaxNumerTrials = str2double(vr.TrialInfo.Answers{find(strcmp(vr.TrialInfo.Prompt,'Max Number of Trials:'))}) ;;           %sets the number of trials...
vr.TrialSettings.iTrial =1 ;                  %is updated everytime is teletransported back at the pos = 0;
%vr.TrialSettings.InterTrialStopMean = 5;      %pause lenght in time...
%vr.TrialSettings.InterTrialStopSigma = .1;    %pause lenght in time...
%vr.TrialSettings.InterTrialStop = normrnd(vr.TrialSettings.InterTrialStopMean,vr.TrialSettings.InterTrialStopSigma,vr.TrialSettings.MaxNumerTrials ,1); % in seconds...
vr.TimeStampsAcrossTrials =[];  %every time a new trial is begun the time stamp of it is stored
vr.RewardMovementOnset = str2double(vr.BehaviourInfo.Answers{find(strcmp(vr.BehaviourInfo.Prompt,'Reward Speed onset:' ))}) ;    %Reward where the speed onset occurs...
vr.RewardMovementSpeedThreshold = 4;    %Minimum speed to elicit reward...
vr.MaxNumberRewardsPerTrial = 50;
vr.MaxTrialLength = str2double(vr.TrialInfo.Answers{find(strcmp(vr.TrialInfo.Prompt,'Max Trial Length (min):'))}) ;
vr.cstart = -eval(vr.exper.variables.chamberLength)/2;
vr.tstart = -eval(vr.exper.variables.floorHeight)/2;
end